### ISSUE TITLE
export command in readme not right

### ISSUE THREAD

**Issue by welchomatic** [polarfire-soc/hart-software-services#47]
The export $PATH command explaining how to use make properly does not point to the proper cross compiler.  In my case, I renamed the directory to match the directory to the path.  This broke the ability to run SoftConsole.  This might be more effort, but could the export $PATH instruction have the actual directory name going forward?
Makes it a bit easier for us learning how to develop for PolarFire.

**Comment by hughbreslin** [comment]
Hey @welchomatic 

are you talking about this export command from the readme?

`$ export PATH=$PATH:$HOME/Microchip/SoftConsole-v2021.3/python/bin:$HOME/Microchip/SoftConsole-v2021.3/riscv-unknown-elf-gcc/bin`

I'm guessing you're using SoftConsole v2022.1, have you tried updating the command to point to this SoftConsole version instead of updating the SoftConsole directory name? I think reverting the SoftConsole directory name change and updating the export command to point to the 2022.1 directory should get things working :) 

We will update the text in the readme to make this clearer.
