### ISSUE TITLE
UART error occurs when HSS is initialized

### ISSUE THREAD

**Issue by ZGDIGE** [polarfire-soc/hart-software-services#76]
Hello,
The uart configuration in HSS is the same as that in putty. When running to the uart_getchar function, a Parity error status appears, resulting in failure to input ymodem.

![3](https://github.com/user-attachments/assets/b4deda24-ea61-40e3-966c-f7cac9391558)

![1](https://github.com/user-attachments/assets/eb503597-f404-493a-ac55-bb0f04f4f8df)
![2](https://github.com/user-attachments/assets/06899b35-d7d2-4225-af66-eb8a1fe7633a)

**Comment by griffini** [comment]
Hi @ZGDIGE ,

This is very strange. And I notice you're getting a UART error even *before* you start YMODEM.

A parity error occurs when the expected calculated parity by the receiver doesn't match the parity bit sent by the transitter. Since you presumably are using 115200 8N1, then parity is disabled and no bit is transmitted, how are you certain that it is a parity error?

I don't seem to see this with my Icicle kit.

With 8N1 I would expect that a parity error is unlikely, and the issue is more likely  to be a framing error or bit-level corruption? Could you be seeing something causing clock drift or incorrect interpretation of start/stop bits? For example, electrical noise or crosstalk or other signal integrity issues? Or a baud rate mismatch (clock inaccuracies or jitter?)? Or improper level shifting/buffering?

**Comment by ZGDIGE** [comment]
> Hi @ZGDIGE ,
> 
> This is very strange. And I notice you're getting a UART error even _before_ you start YMODEM.
> 
> A parity error occurs when the expected calculated parity by the receiver doesn't match the parity bit sent by the transitter. Since you presumably are using 115200 8N1, then parity is disabled and no bit is transmitted, how are you certain that it is a parity error?
> 
> I don't seem to see this with my Icicle kit.
> 
> With 8N1 I would expect that a parity error is unlikely, and the issue is more likely to be a framing error or bit-level corruption? Could you be seeing something causing clock drift or incorrect interpretation of start/stop bits? For example, electrical noise or crosstalk or other signal integrity issues? Or a baud rate mismatch (clock inaccuracies or jitter?)? Or improper level shifting/buffering?

Thank you for your answer. I found that it was a problem with the hardware link. We used a moxa device to convert UART to RS422. After changing the conversion device, there was no problem.

**Comment by griffini** [comment]
Hi @ZGDIGE, Great to hear you have your issue resolved, and thanks for letting me know!
